/*
 * Real, recorded runs comparing how different "brains" perform at exactly
 * the same task: propose a first design step for a fixed brief, through
 * the identical pipeline (same schema, same prompt, same applyStep,
 * same simulate). Two kinds of driver are compared:
 *
 *   1. Hosted API providers (Gemini, DeepSeek for real; Qwen and Grok are
 *      configured but SKIPPED, not faked, because no real key for either
 *      exists in this account as of this writing -- see providers.ts).
 *   2. Claude (this script's own author, reasoning about the same briefs
 *      by hand, run through the identical applyStep/simulate core).
 *
 * This mirrors the book series' own recorded-run discipline (see
 * voice-agents/runs/, agent-evals/runs/): real numbers, real failures kept,
 * small sample size disclosed rather than hidden. Run with:
 *   pnpm exec tsx scripts/compare-providers.ts
 * from the repo root, with apps/web/.env.local's keys loaded.
 */
import { config as loadEnv } from 'dotenv';
import path from 'node:path';
import fs from 'node:fs';
import {
  createProviderGenerator,
  hasRealKey,
  planNextStep,
  PROVIDERS,
  type ProviderId,
  type StepGenerator,
} from '@systemsage/lesson-planner';
import { applyStep, simulate, type Topology } from '@systemsage/engine';

loadEnv({ path: path.join(__dirname, '..', 'apps', 'web', '.env.local') });

const BRIEFS = [
  'A URL shortener that needs to handle 2000 requests per second',
  'A chat application that needs to support 50,000 concurrent users',
] as const;

interface RunResult {
  driver: string;
  brief: string;
  ok: boolean;
  error?: string;
  attempts?: number;
  wallMs?: number;
  stepTitle?: string;
  nodeCount?: number;
  edgeCount?: number;
  stayedSimple?: boolean; // the pedagogical rule: first step should be <=3 nodes
  stats?: { p50: number; p95: number; goodputRps: number; errorRate: number };
}

function countingGenerator(inner: StepGenerator, onCall: () => void): StepGenerator {
  return async (args) => {
    onCall();
    return inner(args);
  };
}

async function runProvider(providerId: ProviderId, brief: string): Promise<RunResult> {
  const config = PROVIDERS[providerId];
  if (!hasRealKey(providerId)) {
    return { driver: config.label, brief, ok: false, error: `No ${config.apiKeyEnvVar} set -- skipped, not faked.` };
  }

  let attempts = 0;
  const generator = countingGenerator(createProviderGenerator(providerId), () => {
    attempts += 1;
  });

  const started = Date.now();
  try {
    const result = await planNextStep(
      { description: brief, priorSteps: [], currentTopology: { nodes: [], edges: [] } },
      { generate: generator },
    );
    const wallMs = Date.now() - started;
    const sim = simulate(result.topology, { seed: 1, simulatedSeconds: 20 });
    return {
      driver: config.label,
      brief,
      ok: true,
      attempts,
      wallMs,
      stepTitle: result.step.stepTitle,
      nodeCount: result.topology.nodes.length,
      edgeCount: result.topology.edges.length,
      stayedSimple: result.topology.nodes.length <= 3,
      stats: {
        p50: sim.stats.p50,
        p95: sim.stats.p95,
        goodputRps: sim.stats.goodputRps,
        errorRate: sim.stats.errorRate,
      },
    };
  } catch (err) {
    return {
      driver: config.label,
      brief,
      ok: false,
      attempts,
      wallMs: Date.now() - started,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/*
 * Claude's own first step for each brief, reasoned about directly (not
 * generated by calling any API), then run through the SAME applyStep +
 * simulate every other driver uses. This is the literal comparison point:
 * an agent (me) deciding what to add, held to the identical structural and
 * simulated standard as an API-driven provider.
 */
function claudeFirstStep(brief: string): { addNodes: Parameters<typeof applyStep>[1]['addNodes']; addEdges: Parameters<typeof applyStep>[1]['addEdges']; stepTitle: string } {
  if (brief.includes('URL shortener')) {
    return {
      stepTitle: 'The Simplest Setup',
      addNodes: [
        { id: 'client-1', kind: 'client', label: 'Clients', config: { rps: 2000 } },
        { id: 'service-1', kind: 'service', label: 'Shortener API' },
        { id: 'db-1', kind: 'db', label: 'URL Store' },
      ],
      addEdges: [
        { from: 'client-1', to: 'service-1' },
        { from: 'service-1', to: 'db-1' },
      ],
    };
  }
  // "A chat application that needs to support 50,000 concurrent users"
  return {
    stepTitle: 'The Simplest Setup',
    addNodes: [
      { id: 'client-1', kind: 'client', label: 'Chat Clients', config: { rps: 500 } },
      { id: 'service-1', kind: 'service', label: 'Chat API' },
      { id: 'db-1', kind: 'db', label: 'Message Store' },
    ],
    addEdges: [
      { from: 'client-1', to: 'service-1' },
      { from: 'service-1', to: 'db-1' },
    ],
  };
}

function runClaude(brief: string): RunResult {
  const started = Date.now();
  const plan = claudeFirstStep(brief);
  const empty: Topology = { nodes: [], edges: [] };
  const result = applyStep(empty, { addNodes: plan.addNodes, addEdges: plan.addEdges, removeEdges: [] });
  const wallMs = Date.now() - started;

  if (!result.ok) {
    return { driver: 'Claude (direct)', brief, ok: false, wallMs, error: result.errors.join(' ') };
  }

  const sim = simulate(result.topology, { seed: 1, simulatedSeconds: 20 });
  return {
    driver: 'Claude (direct)',
    brief,
    ok: true,
    attempts: 1,
    wallMs,
    stepTitle: plan.stepTitle,
    nodeCount: result.topology.nodes.length,
    edgeCount: result.topology.edges.length,
    stayedSimple: result.topology.nodes.length <= 3,
    stats: {
      p50: sim.stats.p50,
      p95: sim.stats.p95,
      goodputRps: sim.stats.goodputRps,
      errorRate: sim.stats.errorRate,
    },
  };
}

async function main() {
  const results: RunResult[] = [];

  for (const brief of BRIEFS) {
    for (const providerId of Object.keys(PROVIDERS) as ProviderId[]) {
      results.push(await runProvider(providerId, brief));
    }
    results.push(runClaude(brief));
  }

  const outPath = path.join(__dirname, '..', 'runs', `provider-comparison-${new Date().toISOString().slice(0, 10)}.json`);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(results, null, 2));

  console.log(`\nn=${results.filter((r) => r.ok).length} successful runs out of ${results.length} attempted (small sample -- see the note this script prints below).\n`);
  console.table(
    results.map((r) => ({
      driver: r.driver,
      brief: r.brief.slice(0, 30) + '...',
      ok: r.ok,
      attempts: r.attempts ?? '-',
      wallMs: r.wallMs ?? '-',
      nodes: r.nodeCount ?? '-',
      simple: r.stayedSimple ?? '-',
      p50: r.stats ? r.stats.p50.toFixed(1) : '-',
      errorRate: r.stats ? (r.stats.errorRate * 100).toFixed(1) + '%' : '-',
      error: r.error ?? '',
    })),
  );
  console.log(`\nFull results: ${outPath}`);
  console.log(
    '\nHONEST CAVEAT: n=2 briefs is not a statistically meaningful sample -- this is a ' +
      'smoke-level comparison (does each driver produce a structurally valid, pedagogically ' +
      'simple, really-simulated first step), not a claim about which model is "better." ' +
      'Treat any single run here the same way this project treats a 6/6 test result: real, ' +
      'but not proof of a general rate.',
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
